### ISSUE TITLE
Problema na formatação

### ISSUE THREAD

**Issue by DennerLemos** [LenonBordini/numero-por-extenso#1]
Parabéns por ter essa iniciativa, sua biblioteca está funcionando perfeitamente, só contatei um caso no qual a formatação não fica do jeito de deveria estar : 1.000.090.000,00 por extenso o certo seria "um bilhão e novem mil reais" , porém sua biblioteca exibe da seguinte forma "um blilhãonoventa mil reais".

**Comment by LenonBordini** [comment]
Obrigado por abrir a issue, fico contente que gostou da iniciativa.

Lancei a correção na versão **1.0.5** e adicionei o seu caso nos testes do pacote.
Estou fechando a issue, qualquer outro problema que tiver, fique a vontade pra reportar.
