### ISSUE TITLE
Escrita errada com numeros percentuais...

### ISSUE THREAD

**Issue by ghost** [LenonBordini/numero-por-extenso#4]
Testei alguns numeros em percentuais tipo:

3.01
50.05
1.049

Ele ignora o primeiro zero após a virgula.
Ficando por exemplo: "tres virgula um porcento", "cinquenta virgula 5 percentual", "um virgula quarenta de nove porcento".

**Comment by LenonBordini** [comment]
Bom teste, obrigado pelo feedback.

O correto seria:

| Número | Por extenso |
|:---:	|:---|
| 3.01 | três **vírgula** um centésimo por cento |
| 50.05 | cinquenta **vírgula** cinco centésimos por cento |
| 1.049 | um **vírgula** quarenta e nove milésimos por cento |

Concorda?

Vou trabalhar nessa correção assim que possível, e lanço ela na versão 1.0.8.

**Comment by LenonBordini** [comment]
Correção efetuada na versão **1.0.8**.

Estou fechando a issue, valeu.
